[package]
name = "throcc-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
throcc-client-core.workspace = true
throcc-proto.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
